### ISSUE TITLE
Camera_Cards questions

### ISSUE THREAD

**Issue by chialinchou1** [NMAAHC/nmaahcmm#29]
1. log file not naming card type
2. Not concatenating when two camera cards in distinct directory are present: camera files were not sorted into original_camera_files; reports for all media files were generated, but only concatenating audio tracks.
3. What does the checksum file contain? What has been hashed? Where is the hash for the final concatenated file? Do we need to also run reports for the final concatenated file?
4. One media file from a MXF (Canon C300) Card has a .xmp file generated, we may also need to save it with the XMLs to original_camera_files
5. Confirming the reason to discard .cpf and .thm and index.mif in the process

@aeschweik @BleakleyMcD

**Comment by aeschweik** [comment]
Hi @chialinchou1 ,

1. Should be addressed in 0e76596a442d1e92474944732ce071faa64f6648
2. Would you be able to provide an example directory structure, or specify the camera card type/s you're encountering this with? (I'm assuming you're talking about an MXF card given the rest of the questions, but seeing the structure might help identify why finding all files with an .mxf extension - the current logic - isn't working.)
3. Taking a closer look at the logic; added an md5 file in the metadata reports folder for the concatenated file in b224723718456142ffba5ebe5ea1d4b81eaee25a (or tar archive if that option is selected, in 25b7033e97e7fc2004e6f2ec65d9dd6fa8fe9bb5).
4. Addressed in 86901b10bd11f823ead66610a18783f57102adb4
5. .cpf is a Custom Picture File; if a "picture profile" has been set, this file will store information about that profile. This file did not seem useful for archival purposes; however, it may be useful if you anticipate doing color grading. .thm is a preview thumbnail; a similar image can easily be re-generated if needed. However, index.mif is an oversight and should be sent to original_camera_files (addressed in ba52e1d36f09c8cdd3e7aaaf79bbf6af8150a5e7). It is a structured file that allows media apps to mount a card; that being said, the card won't be mountable unless the user selects the "tar entire structure" option, rather than restructuring the card into an AIP, and the INDEX.MIF file isn't human-readable so not immediately useful outside of that context.

(I'm referencing http://www.premierepro.org/2016/10/canon-xf-c300-xf305-folder-structure-and-file-naming-explained/ as well as Rob Hoffman's documentation from summer 2020).

Thanks so much - I will update with more on point 3, let me know if you're able to share a sample directory structure for point 2, and also let me know if you think NMAAHC has use cases for the .cpf file in point 5 (if so I can add it to the significant metadata files list).
--Annie

**Comment by BleakleyMcD** [comment]
@chialinchou1 @aeschweik Thank you Chialin and Annie! 

Annie - Chialin is working with the camera card scripts and we'll get back to you again soon. We are meeting with Dave tomorrow to do some testing too.

**Comment by chialinchou1** [comment]
Hi @aeschweik, Thanks for addressing the issues so quickly! I forgot to introduce myself—I'm Chialin, I'm working with @BleakleyMcD and we will test the updates and let you know! 

Below is a screenshot for the file structure in (2):
<img width="814" alt="Screen Shot 2022-01-13 at 11 58 54 AM" src="https://user-images.githubusercontent.com/91981823/149375132-ce6f0bb6-3dbe-47d3-9f3e-2314084f0bbc.png">
:

**Comment by aeschweik** [comment]
Hi Chialin @chialinchou1 , nice to meet you! :) Thanks for the directory screenshot.

Following up on the issues you're listing in #2:

- Not concatenating when two camera cards in distinct directory are present -> currently the script is set up to only process one camera card at a time, but it looks like you have a use case for concatenating files from multiple camera cards. This approach does create a good access copy across multiple cards capturing the same event, but it does lose some context about the provenance of each concatenated file (there's no longer such a clear relationship to the original media). Would you like to add an option to package/concatenate multiple camera cards into one package?
- Camera files were not sorted into original_camera_files -> did the original_camera_files folder end up totally empty, or did some files make it there? Trying to pinpoint where it's failing!
- Reports for all media files were generated, but only concatenating audio tracks -> ! Definitely, for MXF camera cards, if the original MXF files had an audio + video track, the script should concatenate both the audio and video into the concatenated MXF. I can't replicate this at home with the test files I have, but would be interested in testing with the files that failed on your end if you're able to provide them.

**Comment by chialinchou1** [comment]
Hi Annie @aeschweik!

Thanks for following up on #2:
- I think we are hoping the script can detect multiple cards under a folder and run the process for each card separately. Ie. I dropped in Dr_Davis_OH, and I get the result of Card_1 and Card_2 under the output folder as 2 AIPs.
- The original_camera_files folder end up empty
- The files I was testing totaled up to 400Gb, let me discuss with @BleakleyMcD and see if what we can do to send the files to you.


I tested the updates you made:
1. The camera_card type is now listed in the log file (as MXF)
3. see generated md5 file screenshot, it still doesn't list the corresponding file name. 
<img width="682" alt="Screen Shot 2022-01-21 at 10 17 56 PM" src="https://user-images.githubusercontent.com/91981823/150622895-79ddefbe-759b-40bd-8cbe-af8a0daadda5.png">
    Additionally, I get this error message while running the process (I am using a mac):

> Users/chouc/Desktop/nmaahcmm/camera_cards: line 275: /Users/chouc/Desktop/New Folder With 
>     Items/Card_1_test2/metadata/reports//Users/chouc/Desktop/New Folder With 
>     Items/Card_1_test2/objects/Card_1_test2_concatenated.md5: No such file or directory
>     /Users/chouc/Desktop/nmaahcmm/camera_cards: line 275: md5sum: command not found

5. original_camera_files folder now only contains INDEX.MIF

I'll test #4 and let you know!

**Comment by BleakleyMcD** [comment]
Hi @aeschweik @chialinchou1 

Annie, do we need to get you the 400GB files?

**Comment by chialinchou1** [comment]
Hi @aeschweik,

I've discussed with @BleakleyMcD and we would like to take your suggestion to add an option to package/concatenate multiple camera cards into one package.

And follow up on testing for #4 (the xmp file): The updated script resulted in the original_camera_files folder now only contains INDEX.MIF,  no other camera files presented, so I can't tell if the xmp file is sorted into the folder.

For the error message about md5sum, it turns out MAC only has md5 installed not md5sum, I brew installed it, but maybe we need to add that in the required dependency?

**Comment by aeschweik** [comment]
Hi @chialinchou1 and @BleakleyMcD,

Just a few of the files should be enough for testing! Is it ok to send 2 or 3 along to me, or is that still pretty big?

Re: the md5 hashes, you're right, I added md5sum to the dependencies in ffce9728fa450910fa5a7a54f71714aec96829ca. Did the streamhash file list the filename once md5sum was installed?
Re: the xmp file not sorting properly, that's a syntax error on my end, fixed in aee23c354bee2f974639b344f2a507f90a08bc98.

Working on an addition to concatenate multiple camera cards.

Sorry for the belated response! Thanks for your patience and for testing!
--Annie

**Comment by chialinchou1** [comment]
Hi @aeschweik, thank you for the updates! I tested the updates and:

- the xmp file is now sorted properly into the "original_camera_files" folder.
- for the md5 hashes, I can't test if the dependencies works as I've installed md5sum separately earlier. Will find another computer to test on that. But the streamhash file still doesn't list the filenames (it generates the same file content as before), and the file name took part of the file path: 
"OneDrive?-?Smithsonian?Camera?Davis_Card1_concatenated_streamhash.md5" 
I can try and do have it output to a local drive and let you know if it makes any difference.

As for files to test, I'll try to make a folder with a few files and the proper structure and figure out a way to share with you to test.

Thanks again for all your work!
Chialin

**Comment by aeschweik** [comment]
Hi Chialin,

I'm looking at the questions you had about the streamhash file and had two thoughts:

1. I'm hopeful the filenaming issue is fixed in https://github.com/NMAAHC/nmaahcmm/pull/35/commits/771d180554ea71f8c3e367095269e72a8b826736
2. I took a closer look at the streamhash file contents and realized there's possibly a mismatch between what you're expecting and what is there—it's actually a series of hashes for each audio and video stream within the final concatenated video file. There are multiple audio and video streams in the same file, so the streamhash file itself won't list multiple filenames. The video file that contains all these streams has the same filename as the streamhash file...or will be once the filenaming issue is fixed. Does that make sense? Here's some more information on the streamhash utility: https://ffmpeg.org/ffmpeg-formats.html#streamhash-1 It's useful in this case because it allows us to make a comparison of the actual a/v data rather than the complete file with wrapper.

**Comment by chialinchou1** [comment]
Hi Annie,

Thanks for the updates. 
1. md5 file names are still taking part of the directory:
   OneDrive?-?Smithsonian?Camera?TR2021-63_concatenated_streamhash.md5
   New?Folder?With?TR-2021-63_concatenated_streamhash.md5
2. thanks for the explanation, I think I was confused it with a checksum file. I see that this update did generate a
    New?Folder?With?TR-2021-63_concatenated.md5. Would it be able to also include the file name after the checksum? Our 
    DAMs requires it when ingest, and can we save this file to the object folder as well together with its corresponding media 
    file?

**Comment by aeschweik** [comment]
Hi Chialin,

1. Sorry about that, I think I figured out why—it has to do with the spaces in the filepath. Would you mind testing if this commit fixes it? https://github.com/NMAAHC/nmaahcmm/pull/36/commits/d5690fc0359f42dc279dae112231ab0fbfa8e4cf
2. Let me know if the syntax here is what you need for DAMS ingest: https://github.com/NMAAHC/nmaahcmm/pull/36/commits/aa10c66ff96e47a9140ba888cad5ae9d4cb2b1c0

If the syntax of the md5sum output doesn't work (e.g.)
`7812f136273d0067c27d8a60375ae954  /Users/aschweik/Documents/GitHub/nmaahcmm_test_files/AIP_DESTINATION/test5/metadata/reports/A025C071_1908055B_CANON.MXF_ffprobe.xml`
then we can also do the output of md5:
`/Users/aschweik/Documents/GitHub/nmaahcmm_test_files/AIP_DESTINATION/test5/metadata/reports/A025C071_1908055B_CANON.MXF_ffprobe.xml) = 7812f136273d0067c27d8a60375ae954`

Just remind me which one the DAMS needs! :)

**Comment by chialinchou1** [comment]
Hi Annie,
1. It's fixed!!
2. The syntax for checksum output probably should not have the file path, currently the one we're using is in this format:
7812f136273d0067c27d8a60375ae954 A025C071_1908055B_CANON.MXF_ffprobe.xml
(the way its generated from _makechecksum_ in NMAAHCmm)
Thanks for all your work on this!!

**Comment by BleakleyMcD** [comment]
@chialinchou1 can this PR be closed?
